### ISSUE TITLE
IdAndSession.MailboxSession: session is not IMailboxSession

### ISSUE THREAD

**Issue by JoergBrugman** [OfficeDev/ews-managed-api#262]
We have been successfully using email logging in Microsoft Dynamic 365 Business Central with Exchange Online and Public Folders for years. Email logging is an essential business process for many Business Central customers and Microsoft partners. Since March 3, 2021 21:41 we only get the following error message:
**_An internal server error occurred. The operation failed., IdAndSession.MailboxSession: session is not IMailboxSession._**

My research has shown that this error has already existed in 2018 and Microsoft has released a corresponding patch in Exchange Online here.

We need a quick solution from Microsoft for this, as this is business-critical for us!

Thank you in advance for a quick solution.

**Comment by mariusan** [comment]
Hi Joerg

We're also seeing the same issue in code that has worked for years and for us it started 3/3/21 at 19:12 UTC. It happens across several tenants on 365. For us, it fails when doing Copy on a MailItem and the destination is a Public Folder. Worked around it by exporting the item and then importing it into the Public Folder. Would like to see a fix. The issue is probably with EWS, not with the managed API so this might not be the right forum.

**Comment by JonFjolnirAlbertsson** [comment]
We have the same problem with NAV 2018 On-Prem.

**Comment by JoergBrugman** [comment]
> We have the same problem with NAV 2018 On-Prem.

have you already reported the bug to microsoft?

**Comment by JoergBrugman** [comment]
> Hi Joerg
> 
> We're also seeing the same issue in code that has worked for years and for us it started 3/3/21 at 19:12 UTC. It happens across several tenants on 365. For us, it fails when doing Copy on a MailItem and the destination is a Public Folder. Worked around it by exporting the item and then importing it into the Public Folder. Would like to see a fix. The issue is probably with EWS, not with the managed API so this might not be the right forum.

Hi mariusan,
thanks for your offer. Unfortunately, the workaround would not help, as it is a standard component of Microsoft Business Central.

**Comment by AllanReese** [comment]
Hi

I do too have this error and almost in an identical situation as mariusan describes. The only difference is I try to copy several calendar items to a public folder. Due to our logs I can see we have experienced the problem at the exact same time as described by mariusan.

I have not been able to find any other posts/websites with this issue described. Have you and more important has anybody any solution or workaround for this problem?

**Comment by mariusan** [comment]
Hi Allan

The problem persists for me and, like you, I've not found any info online. I can't be asked to raise a ticket with Microsoft as it takes hours and hours of time explaining at many different levels before you actually reach someone who can look at it. Hoping someone else will :-) or if someone can put me in touch with someone who can look at it then I can produce a sample very easily.

Workaround for me has been to export and import instead of copy. Not a great option but it works for my scenario.


﻿﻿Regards
Marius Andresen

[Trigonal]
Trigonal Limited
Mobile: +47 921 53 951  | trigonal.co.uk
The Baltic Exchange | 38 St. Mary Axe | London | EC3A 8EX

Trigonal Ltd is a limited company registered in England with registration number 4758967.
The registered office of Trigonal Ltd is c/o BSG Valentine & Co., Lynton House, 7-12 Tavistock Square, London WC1H 9BQ, UK.
[Sent from Front]
On March 17, 2021, 4:20 PM GMT+1 ***@***.******@***.***> wrote:


Hi

I do too have this error and almost in an identical situation as mariusan describes. The only difference is I try to copy several calendar items to a public folder. Due to our logs I can see we have experienced the problem at the exact same time as described by mariusan.

I have not been able to find any other posts/websites with this issue described. Have you and more important has anybody any solution or workaround for this problem?

**Comment by AllanReese** [comment]
Hi Marius


I perfectly understand your point of view on Microsoft Support. I have been there too with other issues😊 and in this particular case I have done my programming myself which probably will cause a supporter at Microsoft to point towards me and my code. The funny thing is that I experience the problem at the same time as you.

Are you aware of any sites where one can see what updates on the exchange Online servers has been done around the critical time?

In my code – which runs 6 times a day – I can’t incorporate manual tasks like exports and imports. Are you doing the export and import job automatically as well?



​
​Kind regards
Spillerforeningen - The Danish Football Players' Association
For the players
​and the game
​Allan Reese
Senior adviser & CIO
+45 20 24 62 26
www.spillerforeningen.dk
Trygsvej 3, 8230 Aabyhøj, Denmark

Disclaimer
 This e-mail and any attachments is intended solely for the person or entity to whom it is addressed. It may contain privileged and confidential information. If you are not the intended recipient, please be notified that any dissemination, distribution or copying is strictly prohibited. If you have received this e-mail by mistake, please notify the sender immediately and then delete the e-mail and attachments from your system.
Fra: mariusan ***@***.***>
Sendt: 17. marts 2021 16:30
Til: OfficeDev/ews-managed-api ***@***.***>
Cc: Allan Reese ***@***.***>; Comment ***@***.***>
Emne: Re: [OfficeDev/ews-managed-api] IdAndSession.MailboxSession: session is not IMailboxSession (#262)

Hi Allan

The problem persists for me and, like you, I've not found any info online. I can't be asked to raise a ticket with Microsoft as it takes hours and hours of time explaining at many different levels before you actually reach someone who can look at it. Hoping someone else will :-) or if someone can put me in touch with someone who can look at it then I can produce a sample very easily.

Workaround for me has been to export and import instead of copy. Not a great option but it works for my scenario.


﻿﻿Regards
Marius Andresen

[Trigonal]
Trigonal Limited
Mobile: +47 921 53 951 | trigonal.co.uk
The Baltic Exchange | 38 St. Mary Axe | London | EC3A 8EX

Trigonal Ltd is a limited company registered in England with registration number 4758967.
The registered office of Trigonal Ltd is c/o BSG Valentine & Co., Lynton House, 7-12 Tavistock Square, London WC1H 9BQ, UK.
[Sent from Front]
On March 17, 2021, 4:20 PM GMT+1 ***@***.******@***.***<mailto:***@***.******@***.***>> wrote:


Hi

I do too have this error and almost in an identical situation as mariusan describes. The only difference is I try to copy several calendar items to a public folder. Due to our logs I can see we have experienced the problem at the exact same time as described by mariusan.

I have not been able to find any other posts/websites with this issue described. Have you and more important has anybody any solution or workaround for this problem?

**Comment by mariusan** [comment]
Hi Allan

I dont think there is any release log for Exchange online. The closest you get is https://techcommunity.microsoft.com/t5/exchange-team-blog/bg-p/Exchange I think.

By export i simply mean copying the mime content into a string and then to import I create a new empty email in the folder and load the mime content from my temp string. All done in code so no manual intervention.



﻿﻿Regards
Marius Andresen

[Trigonal]
Trigonal Limited
Mobile: +47 921 53 951  | trigonal.co.uk
The Baltic Exchange | 38 St. Mary Axe | London | EC3A 8EX

Trigonal Ltd is a limited company registered in England with registration number 4758967.
The registered office of Trigonal Ltd is c/o BSG Valentine & Co., Lynton House, 7-12 Tavistock Square, London WC1H 9BQ, UK.
[Sent from Front]
On March 17, 2021, 4:41 PM GMT+1 ***@***.******@***.***> wrote:


Hi Marius


I perfectly understand your point of view on Microsoft Support. I have been there too with other issues😊 and in this particular case I have done my programming myself which probably will cause a supporter at Microsoft to point towards me and my code. The funny thing is that I experience the problem at the same time as you.

Are you aware of any sites where one can see what updates on the exchange Online servers has been done around the critical time?

In my code – which runs 6 times a day – I can’t incorporate manual tasks like exports and imports. Are you doing the export and import job automatically as well?



​
​Kind regards
Spillerforeningen - The Danish Football Players' Association
For the players
​and the game
​Allan Reese
Senior adviser & CIO
+45 20 24 62 26
www.spillerforeningen.dk<http://www.spillerforeningen.dk>
Trygsvej 3, 8230 Aabyhøj, Denmark

Disclaimer
This e-mail and any attachments is intended solely for the person or entity to whom it is addressed. It may contain privileged and confidential information. If you are not the intended recipient, please be notified that any dissemination, distribution or copying is strictly prohibited. If you have received this e-mail by mistake, please notify the sender immediately and then delete the e-mail and attachments from your system.
Fra: mariusan ***@***.***>
Sendt: 17. marts 2021 16:30
Til: OfficeDev/ews-managed-api ***@***.***>
Cc: Allan Reese ***@***.***>; Comment ***@***.***>
Emne: Re: [OfficeDev/ews-managed-api] IdAndSession.MailboxSession: session is not IMailboxSession (#262)

Hi Allan

The problem persists for me and, like you, I've not found any info online. I can't be asked to raise a ticket with Microsoft as it takes hours and hours of time explaining at many different levels before you actually reach someone who can look at it. Hoping someone else will :-) or if someone can put me in touch with someone who can look at it then I can produce a sample very easily.

Workaround for me has been to export and import instead of copy. Not a great option but it works for my scenario.


﻿﻿Regards
Marius Andresen

[Trigonal]
Trigonal Limited
Mobile: +47 921 53 951 | trigonal.co.uk<http://trigonal.co.uk/>
The Baltic Exchange | 38 St. Mary Axe | London | EC3A 8EX

Trigonal Ltd is a limited company registered in England with registration number 4758967.
The registered office of Trigonal Ltd is c/o BSG Valentine & Co., Lynton House, 7-12 Tavistock Square, London WC1H 9BQ, UK.
[Sent from Front]
On March 17, 2021, 4:20 PM GMT+1 ***@***.******@***.***<mailto:***@***.******@***.***>> wrote:


Hi

I do too have this error and almost in an identical situation as mariusan describes. The only difference is I try to copy several calendar items to a public folder. Due to our logs I can see we have experienced the problem at the exact same time as described by mariusan.

I have not been able to find any other posts/websites with this issue described. Have you and more important has anybody any solution or workaround for this problem?

**Comment by herojo** [comment]
We see the same Issue since 4th of March (arround 09:50 MEZ, UTC+1). With BC13 and a O365-Tenant (EU Location, not DE).
Any suggestions or plans to solve the problem?

**Comment by AllanReese** [comment]
> We see the same Issue since 4th of March (arround 09:50 MEZ, UTC+1). With BC13 and a O365-Tenant (EU Location, not DE).
> Any suggestions or plans to solve the problem?

I have not come accross any permanant solution provided by Microsoft or even just have a description on what is causing the problem.
I had to alter my code and implement the workaround described by mariusan. Now i don't do a copy of an item I create a new proper item and copy the mimecontent to that new item. I had some issues having it to work but I have got it in place now .... and hopefully we don't see other problems in that area....

**Comment by JoergBrugman** [comment]
> We see the same Issue since 4th of March (arround 09:50 MEZ, UTC+1). With BC13 and a O365-Tenant (EU Location, not DE).
> Any suggestions or plans to solve the problem?

The Business Central team is working on a solution that will come with the next CU in April.

**Comment by JoergBrugman** [comment]
The Business Central team is working on a solution that will come with the next CU in April.
