### ISSUE TITLE
Credential Validation

### ISSUE THREAD

**Issue by jonantoine** [OfficeDev/ews-managed-api#36]
Is there a method to validate login credentials provided by a user without trying to connect (which take about 15 seconds)? Also is there any indication that the users account is locked out so you can notify the user of this?

**Comment by dclaux** [comment]
No, there is no way to validate credentials client-side. If there was we'd have a pretty bad security issue :)
There is also no way to know if an account is locked other than trying to connect to the account.
What operation exactly takes 15 seconds to complete? Is it against Exchange Online, an on-premise deployment?

**Comment by jonantoine** [comment]
Thanks, It is against exchange online and it is when I auto discover the
URL.

**Comment by dclaux** [comment]
Yes, Autodiscover can take a while, but it's actually not because of authentication. The recommendation is to cache the URL you get from Autodiscover and reuse it for as long as it works (and it should work for a long time in O365.) If you start receiving connection errors from EWS repeatedly (e.g. non transient errors) it's probably time to re-autoidscover.

To cache the autodiscovered URL, just do:
```
myService.AutodiscoverUrl(...);
string cachedUrl = myService.Url;
```

Then to reuse it:
```
myService.Url = cachedUrl;
```
