### ISSUE TITLE
Thread safe streaming notification

### ISSUE THREAD

**Issue by fischerman** [OfficeDev/ews-managed-api#48]
The EWS documentation indicates that the library is not thread safe. Opening a streaming notification is a non-blocking operation so I assume that the events are running in another thread.

http://blogs.msdn.com/b/exchangedev/archive/2010/12/22/working-with-streaming-notifications-by-using-the-ews-managed-api.aspx
This article describe how to continuously get streaming notifications by reopen the connection in the onDisconnect event. Isn't that a call coming from another thread? If it's not, is that the right way to get ongoing streaming events?

I appreciate your help
fischerman

**Comment by dclaux** [comment]
Yes, streaming notifications are received on separate threads. The code on the article is fine. But that doesn't make the API thread safe. Essentially, if you plan to use the managed API on multiple threads, each thread should use its own ExchangeService instance, and items created/retrieved using a specific ExchangeService instance shouldn't be shared across threads.

**Comment by fischerman** [comment]
Thank you for your reply.

I fail to see the differentiation. You mention that items should not be shared between threads, yet the code shows that the streaming connection is shared between the "main thread" doing the initial `open` and the "callback thread" reopening the connection.

Can you elaborate please?

**Comment by dclaux** [comment]
The streaming connection is started on the main thread, and it spawns its own thread. At that point, the ExchangeService instance used to create the subscription should not be used for anything else.
OnEvent will be fired on the subscription's own thread. It gives you events, for instance NewMail. At that point, to Load the email you got the notification for, you need to use another ExchangeService instance.

**Comment by fischerman** [comment]
Is that documented somewhere? I don't code much in C# but I think it's important to know that an ExchangeService that is created in the main thread and used for subscription can not be used by the main thread anymore.

Is it safe to close the subscription from the main thread?

**Comment by dclaux** [comment]
The documentation is poor in that area. It's more complicated than that... Every item that you retrieve from the service (with EmailMessage.Bind or exchangeService.BindToItems for instance) is bound to the ExchangeService instance used to retrieve it. So any subsequent operation on that item (for instance, Save, Update, Send, Move, etc.) will be done via that same ExchangeService instance. That's why it is prudent to constrain the use of any given ExchangeService instance to a specific thread.
In the case of your subscription, you will receive events indicating an item has been created, modified, etc., and you'll probably want to bind to new items as a result; to do that, just make sure that you use an ExchangeService instance that will not be used concurrently on another thread. It's not that an ExchangeService instance cannot be used on multiple threads, it's just that it shouldn't be used concurrently on multiple threads.
